apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-configmap-credentials
  annotations:
    policies.kyverno.io/title: Block ConfigMap if there is a Password
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/subject: ConfigMap
    policies.kyverno.io/description: "Block ConfigMap if there is a Password inside the configmap. "
spec:
  validationFailureAction: {{ .Values.validationFailureAction }}
  background: true
  rules:
  - name: check-configmap-credentials
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
    validate:
      message: "ConfigMap should not contain 'password'"
      pattern:
        data:
          X(password): "!?*"
          X(passwd): "!?*"
          X(secret_key): "!?*"
    exclude:
      any:
      - resources:
          namespaces:
            {{- range .Values.excludedNamespaces }}
            - "{{ . }}"
            {{- end }}
